theme: jekyll-theme-midnight
title: Jamie Moffatt
description: Jamie is a Postdoctoral Researcher in Psychology, based at Durham University.
excerpt_separator: <!--more-->
repository: jamie-moffatt/jamie-moffatt.github.io
repository_url: https://github.com/jamie-moffatt/jamie-moffatt.github.io
show_downloads: false
github: [metadata]
