theme: jekyll-theme-midnight
title: Jamie Moffatt on Github
description: PhD student in Psychology, based at the University of Sussex.
excerpt_separator: <!--more-->
repository: jamie-moffatt/jamie-moffatt.github.io
show_downloads: true
