theme: jekyll-theme-cayman
title: Jamie Moffatt on Github
description: Jamie is a PhD student in Psychology, based at the University of Sussex.
excerpt_separator: <!--more-->
repository: jamie-moffatt/jamie-moffatt.github.io
repository_url: "https://github.com/jamie-moffatt/jamie-moffatt.github.io"
