theme: jekyll-theme-midnight
title: Jamie Moffatt
description: Jamie is a psychology PHD student based at the University of Sussex.
excerpt_separator: <!--more-->
repository: jamie-moffatt/jamie-moffatt.github.io
show_downloads: false
